//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ProyectoP6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.EncabezadoFactura = new HashSet<EncabezadoFactura>();
            this.ServiciosOProductos = new HashSet<ServiciosOProductos>();
            this.VehiculosXCliente = new HashSet<VehiculosXCliente>();
        }
    
        public int idCliente { get; set; }
        public string Cedula { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Genero { get; set; }
        public string NombreCompleto { get; set; }
        public string Correo { get; set; }
        public int idProvincia { get; set; }
        public int idCanton { get; set; }
        public int idDistrito { get; set; }
        public string TipoUsuario { get; set; }
        public string Contrasenia { get; set; }
    
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<EncabezadoFactura> EncabezadoFactura { get; set; }
        public virtual ICollection<ServiciosOProductos> ServiciosOProductos { get; set; }
        public virtual ICollection<VehiculosXCliente> VehiculosXCliente { get; set; }
    }
}
