//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ProyectoP6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcaVehiculos
    {
        public MarcaVehiculos()
        {
            this.Vehiculos = new HashSet<Vehiculos>();
        }
    
        public int idMarcaVehiculo { get; set; }
        public string CodigoMarcaVehiculo { get; set; }
        public string TipoMarcaVehiculo { get; set; }
        public int idPaisFabricante { get; set; }
    
        public virtual PaisFabricante PaisFabricante { get; set; }
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }
    }
}
