//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ProyectoP6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiciosOProductos
    {
        public ServiciosOProductos()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }
    
        public int idSOP { get; set; }
        public string CodigoSOP { get; set; }
        public decimal PrecioSOP { get; set; }
        public string TipoSOP { get; set; }
    
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
    }
}
